version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  test-and-check-coverage:
    docker:
      - image: circleci/node:lst
    steps:
      - checkout
      - restore_cache:
        key: dependency-cache-live-{{ checksum "package.json"}}
        - run: yarn
        - save_cache:
          key: dependecy-cache-live={{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./.next/cache
        - run: yarn test-coverage
        - codecov/upload:
          file: './coverage/clover.xml'

workflows:
  test-application:
    jobs:
      - test-and-check-coverage